Name = "Soup.Cpp.Compiler.MSVC"
Language = "C#"
Version = "0.1.10"
Source = [
	"ArgumentBuilder.cs",
	"Compiler.cs",
]

[Dependencies]
Runtime = [
	"Opal@1.0.1",
	"Soup.Cpp.Compiler@0.1.7",
	"Soup.Build.Extensions@0.1.8",
]