Name = "Soup.Cpp.Compiler.MSVC"
Language = "C#"
Version = "0.3.0"
Source = [
	"ArgumentBuilder.cs",
	"Compiler.cs",
]

[Dependencies]
Runtime = [
	"Opal@1.0.3",
	"Soup.Cpp.Compiler@0.3.0",
	"Soup.Build.Extensions@0.2.0",
	"Soup.Build.Extensions.Utilities@0.1.0",
]