Version = 1
[Projects]
"C#" = [
	{ Name = "Soup.Cpp", Version = "../Extension" },
	{ Name = "Opal", Version = "1.0.3" },
	{ Name = "Soup.Build", Version = "0.1.3" },
	{ Name = "Soup.Build.Extensions", Version = "0.2.0" },
	{ Name = "Soup.Build.Extensions.Utilities", Version = "0.2.0" },
	{ Name = "Soup.Cpp.Compiler", Version = "0.3.0" },
	{ Name = "Soup.Cpp.Compiler.MSVC", Version = "0.3.0" },
]
