Version = 2
[Closures]
[Closures.Root]
"C#" = [
	{ Name = "Soup.Cpp", Version = "../Extension", Build = "Build0" },
	{ Name = "Opal", Version = "1.0.3", Build = "Build0" },
	{ Name = "Soup.Build", Version = "0.1.4", Build = "Build0" },
	{ Name = "Soup.Build.Extensions", Version = "0.2.0", Build = "Build0" },
	{ Name = "Soup.Build.Extensions.Utilities", Version = "0.2.1", Build = "Build0" },
	{ Name = "Soup.Cpp.Compiler", Version = "0.3.1", Build = "Build0" },
	{ Name = "Soup.Cpp.Compiler.MSVC", Version = "0.3.1", Build = "Build0" },
]
[Closures.Build0]
"C#" = [
	{ Name = "C#", Version = "0.1.0" },
]
